tasks:
  install-dependencies:
    name: Install dependencies
    command: npm ci
    triggeredBy:
      - manual
      - postDevcontainerStart
      - prebuild

  build:
    name: Build application
    command: npm run build
    dependsOn:
      - install-dependencies
    triggeredBy:
      - manual

services:
  app:
    name: TanStack Start
    description: TanStack Start development server
    triggeredBy:
      - manual
      - postEnvironmentStart
    commands:
      start: |
        ona environment port open 3000 --admission creator_only --name "TanStack Start"
        export ONA_EXPOSED_HOST="$(ona environment port get 3000 -f URL | cut -c 9-)"
        export __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS="$ONA_EXPOSED_HOST"
        exec npm run dev -- --host 0.0.0.0
      ready: curl -fsS http://localhost:3000
